### ISSUE TITLE
No module named pyee

### ISSUE THREAD

**Issue by rminformaticos** [bobaos/bdsd.python#1]
Hello, i installed bobaos knx 838 correctly, i execute bdsd-cli and read data.

Im triying to read with python script, i downloaded all files, but i have this error:

![image](https://user-images.githubusercontent.com/3592897/79544938-1a1d5f80-8090-11ea-914e-65535187f983.png)

Can help me, please???

**Comment by shabunin** [comment]
Hi,

```text
sudo pip install pyee
```

https://pyee.readthedocs.io/en/latest/

sorry for lack of documentation. I'm not a python guy, still, it is example of how client in programming language different from js can be done.

PS: I'm not mantaining bdsd.sock anymore. There might be some issues with connections, as I remember. Still, it is good to experiment and learn.

You may upgrade to https://github.com/dobaos - I have rewritten sdk in D language (advantages - less RAM consumption, more mature api protocol) and there is python example as well.

**Comment by rminformaticos** [comment]
Hi, i create an app with nodejs and i can read and communicate correctly 100%.

I will test dobaos.

Thanks for help

**Comment by shabunin** [comment]
If I am not mistaken, bdsd.sock may not detect correctly BAOS reset events (knx bus disconnected and connected again, application download from ETS). Try it yourself and see behaviour. 

https://drive.google.com/drive/folders/1LxJj-hWxdFW1As1zJIehzDWGsSe2RmR9

For raspbian download latest binary dobaos.arm.rpi_10mar2020_glibc224

Some example I publish on forum https://forum.knx-user.club/, take a look too.
